set nocompatible              " be iMproved, required
filetype on                   " required
syntax on
"colorscheme molokai
"set background=dark
"set background=light
"colorscheme solarized

"set tab to 4 spaces
set ts=4
set expandtab
set autoindent
"To enable/disable folding use Vim's standard folding configuration.
set nofoldenable
set hlsearch
" " 显示光标当前位置
set ruler
" " 开启行号显示
set number
" " 高亮显示当前行/列
set cursorline
"set cursorcolume
let mapleader = ','

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
"Plugin 'user/L9', {'name': 'newL9'}

"Plugin 'Python-mode-klen'
Plugin 'klen/python-mode'
"Turn off some pymode Errors
let g:pymode_lint_ignore = "W,E501,E265,E221,E251,E231,E225"
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 9
"set laststatus=2

Plugin 'scrooloose/nerdtree'

"Markdown Plugins
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

" 接口与实现快速切换
Plugin 'https://github.com/vim-scripts/a.vim'
" *.cpp 和 *.h 间切换
nmap <Leader>ch :A<CR>
" " 子窗口中显示 *.cpp 或 *.h
nmap <Leader>sch :AS<CR>

"显示书签的插件
Plugin 'https://github.com/kshenoy/vim-signature'
" m[a-zA-Z] 添加/删除书签
" `[a-zA-Z] 跳转到书签

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
map <leader>t :NERDTree<cr>
" map the multi-tab commands
map <leader>w <C-w>
map <leader>h <C-w>h
map <leader>l <C-w>l
map <leader>j <C-w>j
map <leader>k <C-w>k


"Run command according to different filetype
func! Run()
    if &filetype == 'python'
        exec "!python %"
    elseif &filetype == 'markdown'
        exec "!nd %"
    endif
endfunc

map <F5> :call Run()<CR>

"使用'y[数字]<cr>可以复制一个块
"使用+p可以粘贴
"


" " 显示光标当前位置
set ruler
" " 开启行号显示
set number
" " 高亮显示当前行/列
set cursorline
" set cursorcolumn
